const { pool } = require('../../config/database');

function toDateKey(value) {
  if (!value) return null;
  return new Date(value).toISOString().slice(0, 10);
}

async function runAutomationCycle() {
  const connection = await pool.getConnection();

  try {
    await connection.beginTransaction();

    const [rules] = await connection.query(
      `SELECT rule_id, reminder_level, days_after_due
       FROM reminder_rules
       ORDER BY reminder_level`
    );

    const [tickets] = await connection.query(
      `SELECT ticket_id, receipt_no, branch_id, customer_id, status, due_date
       FROM pawn_tickets
       WHERE status IN ('ACTIVE', 'RENEWED', 'OVERDUE')
         AND due_date IS NOT NULL`
    );

    const [existingLogs] = await connection.query(
      `SELECT ticket_id, reminder_level
       FROM sms_reminder_logs
       WHERE status IN ('SCHEDULED', 'SENT', 'FAILED')`
    );

    const existingLogMap = new Set(
      existingLogs.map((row) => `${row.ticket_id}:${row.reminder_level}`)
    );

    const todayKey = toDateKey(new Date());

    for (const ticket of tickets) {
      const dueKey = toDateKey(ticket.due_date);
      if (!dueKey) continue;

      const dueDate = new Date(dueKey);
      const today = new Date(todayKey);
      const daysOverdue = Math.floor((today - dueDate) / (1000 * 60 * 60 * 24));

      if (daysOverdue > 0 && ticket.status !== 'OVERDUE') {
        await connection.query(
          `UPDATE pawn_tickets SET status = 'OVERDUE' WHERE ticket_id = ?`,
          [ticket.ticket_id]
        );
        await connection.query(
          `INSERT INTO ticket_status_history (ticket_id, old_status, new_status, changed_by_staff_id, remark)
           VALUES (?, ?, 'OVERDUE', NULL, 'Automatic overdue transition')`,
          [ticket.ticket_id, ticket.status]
        );
      }

      for (const rule of rules) {
        if (daysOverdue < rule.days_after_due) continue;

        const logKey = `${ticket.ticket_id}:${rule.reminder_level}`;
        if (existingLogMap.has(logKey)) continue;

        await connection.query(
          `INSERT INTO sms_reminder_logs
             (ticket_id, branch_id, customer_id, reminder_level, rule_id, scheduled_at, sent_at, status, provider_response)
           VALUES (?, ?, ?, ?, ?, DATE_ADD(?, INTERVAL ? DAY), NOW(), 'SENT', 'Auto-generated by scheduler')`,
          [
            ticket.ticket_id,
            ticket.branch_id,
            ticket.customer_id,
            rule.reminder_level,
            rule.rule_id,
            ticket.due_date,
            rule.days_after_due
          ]
        );

        existingLogMap.add(logKey);
      }
    }

    await connection.commit();
    return { success: true };
  } catch (error) {
    await connection.rollback();
    throw error;
  } finally {
    connection.release();
  }
}

function startAutomationScheduler() {
  const intervalMs = 60 * 60 * 1000;

  runAutomationCycle().catch((error) => {
    console.error('❌ Initial automation cycle failed:', error.message);
  });

  return setInterval(() => {
    runAutomationCycle().catch((error) => {
      console.error('❌ Scheduled automation cycle failed:', error.message);
    });
  }, intervalMs);
}

module.exports = {
  runAutomationCycle,
  startAutomationScheduler
};